### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by myktw** [AmazingPP/subVerison_GTAV_Hack#1]
在全屏模式无法显示界面，运行一段时间后游戏就崩溃了什么都不提示是我打开的方式不对吗？

**Comment by AmazingPP** [comment]
由于UI是外部绘制，所以必须使用全屏无边框或者窗口化模式。目前已知部分人玩赌场豪杰最终任务时会崩溃，你崩溃时开启了哪些功能？

**Comment by myktw** [comment]
windows10,steam版本
玩家-无敌
玩家-永不通缉
武器-无扩散
武器-无后座
武器-无需换弹
武器-快速换弹拉满
武器-武器伤害倍数拉满
武器-无线弹药
武器-射程拉满
武器-爆炸子弹
武器-燃烧子弹
载具-属性-牵引力
杂项-线上-可调参数-AFK反挂机踢出
杂项-线上-可调参数-天基炮无冷却

退出时GTA无显示崩溃开启以上功能单纯挂机都蹦

**Comment by AmazingPP** [comment]
崩溃前有任何错误提示么？貌似和我汇报有崩溃问题都是Steam版本的用户，我自己是Epic版本，从未遇到过崩溃问题。下个版本将会加Log功能，方便排查问题

**Comment by myktw** [comment]
无任何提示直接闪退
闪退后GTA没有任何提示只有一个subVerison检测不到游戏的提示

**Comment by AmazingPP** [comment]
有尝试过老版本的subVersion么？

**Comment by myktw** [comment]
1.0也会

**Comment by AmazingPP** [comment]
请添加我的discord   mAsk°#4609

**Comment by AmazingPP** [comment]
已修复 [#4f225ee](https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/1d836837cc115545dda3a269201eff0a63ad8e97)
