### ISSUE TITLE
被人套模的防御有没有啊被套模太恶心了能搞个攻击者自爆的功能就更好了

### ISSUE THREAD

**Issue by dxzm2013gmailcom** [AmazingPP/subVerison_GTAV_Hack#17]

**Comment by AmazingPP** [comment]
你需要搞清楚外置和内置的区别，外置没法做到内置强大的功能，因为内置需要注入dll，而外置不需要。我在研究如何解除套模，但攻击者自爆肯定是不可能的

**Comment by dxzm2013gmailcom** [comment]
> 你需要搞清楚外置和内置的区别，外置没法做到内置强大的功能，因为内置需要注入dll，而外置不需要。我在研究如何解除套模，但攻击者自爆肯定是不可能的

那传送行吗我坐车黏在他身上也可以恶心他（如果我不被移出车辆的话)
