### ISSUE TITLE
建议延时下解锁功能的请求速度

### ISSUE THREAD

**Issue by Aunixtoyou** [AmazingPP/subVerison_GTAV_Hack#19]
解锁速度太快会触发R星的警告。
另外，我53张扑克竟然成功解锁了豪赌客，有点意外 2333
![image](https://user-images.githubusercontent.com/17799702/91656418-25c36d00-eaeb-11ea-8bfa-7fde72c411cf.png)

**Comment by AmazingPP** [comment]
已经是1秒处理一个了，算是很慢了，再慢就太慢了

你可以尝试一次别把所有衣物，奖品，车辆啥的都解锁
