### ISSUE TITLE
必须以管理员身份运行

### ISSUE THREAD

**Issue by egcn** [AmazingPP/subVerison_GTAV_Hack#2]
系统: Win10 2004 

一开始用的时候，直接点开就可以。之后一次突然提示“必须运行GTA5.exe"，反复试了几次没成功，推测权限不够（注入失败等原因），启用管理员，果然成功了

**Comment by AmazingPP** [comment]
Release配置下链接器UAC执行级别没有设为requireAdministrator (/level='requireAdministrator')导致

已解决[#4d532cb](https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/4d532cb39512493a1de89c8afcee33600dc68b3c)
