### ISSUE TITLE
v1.3.1出现的问题

### ISSUE THREAD

**Issue by 2200404400** [AmazingPP/subVerison_GTAV_Hack#20]
1.超级跳跃开启后会导致游戏崩溃
2.无扩散开启后无效果
3.武器伤害倍数开启后无效果

**Comment by AmazingPP** [comment]
> 1.超级跳跃开启后会导致游戏崩溃
> 2.无扩散开启后无效果
> 3.武器伤害倍数开启后无效果

**已修复** 2.无扩散无效果 [b0d6b1e](https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/b0d6b1e695c2f0181f3473a518b215c1589f8561)
**已修复** 3.武器伤害倍数无效果 [b0d6b1e](https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/b0d6b1e695c2f0181f3473a518b215c1589f8561)

1.关于崩溃，你可以提供一下你的电脑配置吗？

**Comment by 2200404400** [comment]
很高兴您能收到我的信息，我在附件内附上了电脑配置.&nbsp; &nbsp; &nbsp;PS:问题1在线下模式开启后读取存档2-3次就会崩溃。

若您修复了这些问题请尽快发布更新！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmazingPP/subVerison_GTAV_Hack"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月31日(星期一) 凌晨0:11
收件人:&nbsp;"AmazingPP/subVerison_GTAV_Hack"<subVerison_GTAV_Hack@noreply.github.com&gt;;
抄送:&nbsp;"‭"<2200404400@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AmazingPP/subVerison_GTAV_Hack] v1.3.1出现的问题 (#20)





  
1.超级跳跃开启后会导致游戏崩溃
 2.无扩散开启后无效果
 3.武器伤害倍数开启后无效果
  
已修复 2.无扩散无效果 b0d6b1e
 已修复 3.武器伤害倍数无效果 b0d6b1e
 
1.关于崩溃，你可以提供一下你的电脑配置吗？

**Comment by 2200404400** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmazingPP/subVerison_GTAV_Hack"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月31日(星期一) 凌晨0:11
收件人:&nbsp;"AmazingPP/subVerison_GTAV_Hack"<subVerison_GTAV_Hack@noreply.github.com&gt;;
抄送:&nbsp;"‭"<2200404400@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AmazingPP/subVerison_GTAV_Hack] v1.3.1出现的问题 (#20)





  
1.超级跳跃开启后会导致游戏崩溃
 2.无扩散开启后无效果
 3.武器伤害倍数开启后无效果
  
已修复 2.无扩散无效果 b0d6b1e
 已修复 3.武器伤害倍数无效果 b0d6b1e
 
1.关于崩溃，你可以提供一下你的电脑配置吗？

**Comment by AmazingPP** [comment]
不好意思，我在Github里无法看到你的电脑配置，请你讲配置图发送到1620535041@qq.com，谢谢

**Comment by AmazingPP** [comment]
> CPU:i7-9750H 显卡:GTX 1650G 内存:16G DDR4 2666MHz 系统：Win10 64位

这样的配置应该完全没有问题，目前还无法确定崩溃的具体原因。

如果频繁崩溃请停止使用 **超级跳跃、爆炸近战、爆炸子弹及燃烧子弹**这四个功能。
