### ISSUE TITLE
MenuSelect功能失效

### ISSUE THREAD

**Issue by Ku1o** [AmazingPP/subVerison_GTAV_Hack#21]
MenuSelect无效，导致无法在游戏中开关功能，只能在settings中修改01开关功能，不清楚具体原因，已尝试更改按键后亦无效。

**Comment by AmazingPP** [comment]
> MenuSelect无效，导致无法在游戏中开关功能，只能在settings中修改01开关功能，不清楚具体原因，已尝试更改按键后亦无效。

怎么Close掉了

**Comment by Ku1o** [comment]
因为蠢了(。_。)，可能刚好测试的ENTER和\键都是不适用的，后面该成N就可以了

**Comment by AmazingPP** [comment]
`ENTER`键和`\`键确实不支持。完整的快捷键自定义支持列表请看[stdafx.cpp](https://github.com/AmazingPP/subVerison_GTAV_Hack/blob/master/subVersion/stdafx.cpp)

虽然不是大问题，但还是感谢你的积极反馈。:smile:
