### ISSUE TITLE
电击枪无法获取

### ISSUE THREAD

**Issue by lixiangwuxian** [AmazingPP/subVerison_GTAV_Hack#22]
线上模式使用杂项-武器获取-手枪-电击枪，没有获取电击枪，而是获取了2000游戏币

**Comment by AmazingPP** [comment]
获得武器都有一定几率失败，多按几次即可（By Design）。

我这里测试时可以获得电击枪的，你再多试试呢

**Comment by lixiangwuxian** [comment]
> 
> 
> 获得武器都有一定几率失败，多按几次即可（By Design）。
> 
> 我这里测试时可以获得电击枪的，你再多试试呢

测试多次，不仅限于电击枪，除第一次成功获取火神机枪外均失败，直到出现警告仍未成功

**Comment by AmazingPP** [comment]
> > 获得武器都有一定几率失败，多按几次即可（By Design）。
> > 我这里测试时可以获得电击枪的，你再多试试呢
> 
> 测试多次，不仅限于电击枪，除第一次成功获取火神机枪外均失败，直到出现警告仍未成功

可以提供一下系统版本和计算机配置么

**Comment by lixiangwuxian** [comment]
> 
> 
> > > 获得武器都有一定几率失败，多按几次即可（By Design）。
> > > 我这里测试时可以获得电击枪的，你再多试试呢
> > 
> > 
> > 测试多次，不仅限于电击枪，除第一次成功获取火神机枪外均失败，直到出现警告仍未成功
> 
> 可以提供一下系统版本和计算机配置么

系统是win10专业版1909
计算机配置是 CPU i5 9700kf 内存 2*2966 ddr4 8g 显卡是蓝天1070oc

**Comment by AmazingPP** [comment]
请尝试一下人坐进载具中，然后点击获取一些武器，等类似于钱的可拾取物落在地上时，再下车拾取。看看这样能不能获取到武器

**Comment by Aunixtoyou** [comment]
> 请尝试一下人坐进载具中，然后点击获取一些武器，等类似于钱的可拾取物落在地上时，再下车拾取。看看这样能不能获取到武器

能拾取到钱，但是拾取不到武器。我的是最近更新后出现获取不到武器了。

**Comment by AmazingPP** [comment]
> > 请尝试一下人坐进载具中，然后点击获取一些武器，等类似于钱的可拾取物落在地上时，再下车拾取。看看这样能不能获取到武器
> 
> 能拾取到钱，但是拾取不到武器。我的是最近更新后出现获取不到武器了。

添加一下我的QQ1620535041

**Comment by Aunixtoyou** [comment]
> > > 请尝试一下人坐进载具中，然后点击获取一些武器，等类似于钱的可拾取物落在地上时，再下车拾取。看看这样能不能获取到武器
> > 
> > 
> > 能拾取到钱，但是拾取不到武器。我的是最近更新后出现获取不到武器了。
> 
> 添加一下我的QQ1620535041

更新了之后我的能获取到武器了，我是epic版

**Comment by AmazingPP** [comment]
增加了获取武器时修改武器pickup_model的延迟，就OK了，从100毫秒增加到150毫秒
