### ISSUE TITLE
UI问题

### ISSUE THREAD

**Issue by MonSterSeVen** [AmazingPP/subVerison_GTAV_Hack#23]
UI后面有黑色模块占用屏幕
![QQ截图20200905175641](https://user-images.githubusercontent.com/70800550/92302757-254d2b00-ef5e-11ea-861e-4d66d1c725eb.png)

**Comment by AmazingPP** [comment]
>  UI后面有黑色模块占用屏幕
> 
> ![QQ截图20200905175641](https://user-images.githubusercontent.com/70800550/92302757-254d2b00-ef5e-11ea-861e-4d66d1c725eb.png)
> 
> 

请检查DX9组件是否有缺失或损坏，建议尝试重装DX9

**Comment by MonSterSeVen** [comment]
> > UI后面有黑色模块占用屏幕
> > ![QQ截图20200905175641](https://user-images.githubusercontent.com/70800550/92302757-254d2b00-ef5e-11ea-861e-4d66d1c725eb.png)
> 
> 请检查DX9组件是否有缺失或损坏，建议尝试重装DX9

win7无法回滚DX版本，参考前面关闭的回复，更新显卡驱动后解决，但貌似驱动不兼容，蓝屏了XD

**Comment by AmazingPP** [comment]
...你先解决蓝屏问题吧，应该和显卡驱动没关系，你去找个DX修复工具修复一下试试。

**Comment by MonSterSeVen** [comment]
网上查了很多DX修复也操作了，没有效果，将显卡驱动更新至451版本后，黑色模块消失，UI正常显示，我现在正尝试回滚较老一点的显卡驱动，现在是解决蓝屏问题了.....XD

**Comment by AmazingPP** [comment]
蓝屏代码多少

**Comment by MonSterSeVen** [comment]
0x00000116

**Comment by AmazingPP** [comment]
加油解决吧，应该是显卡驱动导致的蓝屏，我先关闭issue了🤣
