### ISSUE TITLE
关于之前UI显示错误的问题 

### ISSUE THREAD

**Issue by icepiggy** [AmazingPP/subVerison_GTAV_Hack#24]
之前我发的那个关于UI显示错误的Issues回帖的不是我本人，另外黑块的原因找到了，不是DX损坏的问题也不是驱动版本的问题（本人已经尝试过多个版本），是NVIDIA控制面板中一个叫FXAA的选项的关系，如果出现和我一样的黑块挡屏问题请关闭FXAA的选项，希望PP能在后续版本中尝试下解决此问题

**Comment by AmazingPP** [comment]
got it
