### ISSUE TITLE
刷车bug

### ISSUE THREAD

**Issue by caochuang0630** [AmazingPP/subVerison_GTAV_Hack#26]
在非陆地比如桥上就无法刷车

**Comment by AmazingPP** [comment]
因为刷到了桥下面。。我刷车默认Z轴是-255，会传送到当前最低的陆地上。如果是在桥上，就是刷在桥下了

**Comment by Gjleen** [comment]
你好，那个这个需要怎么下载啊？？

**Comment by AmazingPP** [comment]
> 你好，那个这个需要怎么下载啊？？

https://github.com/AmazingPP/subVerison_GTAV_Hack/releases/tag/v1.3.3

**Comment by Gjleen** [comment]
谢谢大神
