### ISSUE TITLE
kiss

### ISSUE THREAD

**Issue by kisslangm** [AmazingPP/subVerison_GTAV_Hack#28]
赌场豪劫的功能没效果，别的号都有，就我自己的号解锁不黑屏一下没效果，怎么办

**Comment by kisslangm** [comment]
The function of casino robbery has no effect. There are other numbers. It doesn't work if I unlock my own number. What should I do

**Comment by AmazingPP** [comment]
> 赌场豪劫的功能没效果，别的号都有，就我自己的号解锁不黑屏一下没效果，怎么办

确保你在使用赌场豪杰功能时的不在面板界面里。一定要是可以正常移动人物的状态下使用

**Comment by kisslangm** [comment]
没在面板界面&nbsp; 可以走动 下&nbsp; 试过&nbsp; 也没效果&nbsp; &nbsp; 别的号 开始处理到1的时候 会黑屏一下&nbsp; 面板就解锁完了有了&nbsp; &nbsp;我的号 开始处理 1 没黑屏 也没反应



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mAsk°"<notifications@github.com&gt;; 
发送时间: 2020年9月25日(星期五) 中午1:16
收件人: "AmazingPP/subVerison_GTAV_Hack"<subVerison_GTAV_Hack@noreply.github.com&gt;; 
抄送: "虹"<971221816@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AmazingPP/subVerison_GTAV_Hack] kiss (#28)





  
赌场豪劫的功能没效果，别的号都有，就我自己的号解锁不黑屏一下没效果，怎么办
  
确保你在使用赌场豪杰功能时的不在面板界面里。一定要是可以正常移动人物的状态下使用

**Comment by AmazingPP** [comment]
你的号有没有至少一次自己作为主持完成一整把赌场豪劫，如果没有需要先完整做一把

**Comment by kisslangm** [comment]
有的 自己主持做完过气势汹汹&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mAsk°"<notifications@github.com&gt;; 
发送时间: 2020年9月25日(星期五) 中午1:21
收件人: "AmazingPP/subVerison_GTAV_Hack"<subVerison_GTAV_Hack@noreply.github.com&gt;; 
抄送: "虹"<971221816@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AmazingPP/subVerison_GTAV_Hack] kiss (#28)





 
你的号有没有至少一次自己作为主持完成一整把赌场豪劫，如果没有需要先完整做一把

**Comment by AmazingPP** [comment]
那就不清楚了，你可以换个游戏厅试试。

**Comment by kisslangm** [comment]
OK&nbsp; 谢谢你的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mAsk°"<notifications@github.com&gt;; 
发送时间: 2020年9月25日(星期五) 中午1:25
收件人: "AmazingPP/subVerison_GTAV_Hack"<subVerison_GTAV_Hack@noreply.github.com&gt;; 
抄送: "虹"<971221816@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AmazingPP/subVerison_GTAV_Hack] kiss (#28)





 
那就不清楚了，你可以换个游戏厅试试。

**Comment by AmazingPP** [comment]
没关系，感谢你的反馈。如果还有其他问题欢迎提交New issue
