### ISSUE TITLE
希望刷出来的车能满改

### ISSUE THREAD

**Issue by BaiBuCYBGT** [AmazingPP/subVerison_GTAV_Hack#3]
挺好的，就是有些载具刷出来没有改过的，要是能改过就好了，试车的时候方便一点

**Comment by AmazingPP** [comment]
因为每一辆车的配件数量、配件形式都不一样，很复杂。如果我单独对每一辆车的满改状态进行适配，工作就很机械，而且很愚蠢。事实上我尝试过有没有简单、通用的方法去将车辆满改。但我一直没有找到，当我发现有简单的办法时，我会将自动满改的功能加进去的

**Comment by BaiBuCYBGT** [comment]
> 
> 
> 因为每一辆车的配件数量、配件形式都不一样，很复杂。如果我单独对每一辆车的满改状态进行适配，工作就很机械，而且很愚蠢。事实上我尝试过有没有简单、通用的方法去将车辆满改。但我一直没有找到，当我发现有简单的办法时，我会将自动满改的功能加进去的

之前用的另外一个叫做kiddion的，里面刷出来的都是满改的，大佬或许能去参考一下？
还有赌场控制转盘，老虎机，增加老虎机的次数不知道大佬以后会不会加这些功能进去..

**Comment by AmazingPP** [comment]
首先 谢谢你的反馈

同#16 改进了载具生成，现在刷出来的车是满改了，commit见[3589c11](https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/3589c11aff5918dbec32fc358f18ae8a037ae578)
