### ISSUE TITLE
赌场，

### ISSUE THREAD

**Issue by kisslangm** [AmazingPP/subVerison_GTAV_Hack#30]
选择物品，或方式后自动解锁了，枪手，哪些可选的，还有支援组的分红太高了，金库刷车想带人进去卡主拿物品的时间。通过那个通道后金库门前刷车有时候能够靠向前传送卡出来，有时候就是在赌场楼顶上刷不出来。

**Comment by kisslangm** [comment]
支援组加个莱斯特分红就要了60-80万

**Comment by AmazingPP** [comment]
莱斯特分红无法修改。第二块面板除了黑客之外所有的分红已经是最低分红了。室内是不好刷车的。

**Comment by AmazingPP** [comment]
请不要再反馈非功能性BUG，使用上的小问题请自行解决。
