### ISSUE TITLE
赌场豪杰全部卡成最高之后 无法开启

### ISSUE THREAD

**Issue by hongsangdesu** [AmazingPP/subVerison_GTAV_Hack#31]
赌场豪杰全部卡成最高之后 无法开启 四个人齐全之后无法开启战局  过了一会自动退出 左上角提示没有玩家
这边建议吧刷钱弄多点 10w不过瘾

**Comment by laridzhang** [comment]
遇到了类似的问题，不过我启动最终任务后的提示是“主持人已离开”

**Comment by AmazingPP** [comment]
[v1.3.5.2已修复](https://github.com/AmazingPP/subVerison_GTAV_Hack/releases/tag/v1.3.5.2)
