### ISSUE TITLE
赌场抢劫初次跳过前置后启动战局卡死

### ISSUE THREAD

**Issue by lixiangwuxian** [AmazingPP/subVerison_GTAV_Hack#32]
将dc任务板上前置任务跳过后，启动dc抢劫战局，画面会停止在虚化的在游戏厅的地下室，仍有声音，无法进入任务

**Comment by AmazingPP** [comment]
emm，因为v1.3.1后把dc抢劫的跳过改成了除了黑客其他人都是空的，所以第一次玩dc如果就跳过会卡主，下个版本fix

**Comment by AmazingPP** [comment]
[v1.3.5.2已修复](https://github.com/AmazingPP/subVerison_GTAV_Hack/releases/tag/v1.3.5.2)
