### ISSUE TITLE
赌场修改失效

### ISSUE THREAD

**Issue by hu16839007** [AmazingPP/subVerison_GTAV_Hack#34]
1，赌场除了兵不厌诈有把陶瓷手枪，潜行和气势汹汹都没有枪
2，赌场分红与实际到账金额不对，可以认为修改分红无效
3，有时候有杜根bug,好像一键全高没有

**Comment by AmazingPP** [comment]
1.我这里是有枪的
2.修改分红必须自己是主机，而且要全程打开
3.杜根是啥
