### ISSUE TITLE
rp倍数无效果

### ISSUE THREAD

**Issue by a2489003662** [AmazingPP/subVerison_GTAV_Hack#35]
开启rp倍数 反而会没有rp= = 希望大佬能修复一下~~感恩

**Comment by AmazingPP** [comment]
> 开启rp倍数 反而会没有rp= = 希望大佬能修复一下~~感恩

适当开低些，任务结算超过R*阈值会拿不到RP。所以最高RP倍数只适合任务里杀NPC涨经验

**Comment by a2489003662** [comment]
我就開了一檔～～～



发自我的iPhone


------------------ 原始邮件 ------------------
寄件人： mAsk° <notifications@github.com&gt;
发送时间: 2020年12月3日 18:35
收件人： AmazingPP/subVerison_GTAV_Hack <subVerison_GTAV_Hack@noreply.github.com&gt;
抄送: a2489003662 <2489003662@qq.com&gt;, Author <author@noreply.github.com&gt;
主旨： 回覆：[AmazingPP/subVerison_GTAV_Hack] rp倍数无效果 (#35)





  
开启rp倍数 反而会没有rp= = 希望大佬能修复一下~~感恩
  
适当开低些，任务结算超过R*阈值会拿不到RP。所以最高RP倍数只适合任务里杀NPC涨经验
