### ISSUE TITLE
挺不错的项目，很厉害

### ISSUE THREAD

**Issue by zjh4473** [AmazingPP/subVerison_GTAV_Hack#36]
学习了
不过单论修改器，这玩意很弱啊。
功能无论如何比不过内置。
而且看起来没有反检测？那岂不是玩两天号没了。
建议作者改成线下修改器，不要说线上了，不然别人号没了要来骂的。

**Comment by AmazingPP** [comment]
感谢质疑

内置没开源罢了。
由于Windows内核限制，外置无论如何是比不过内置的，我的外置只是功能多罢了。
GTAV没有Client端的反作弊系统，不需要Anti-AntiCheat。
subVersion用户有至少上千人，无直接证据表明会封禁。
