### ISSUE TITLE
你好，感谢你的奉献，但我在用devc++编译时会报错

### ISSUE THREAD

**Issue by nanshenisaGAY** [AmazingPP/subVerison_GTAV_Hack#40]
可能需要改成前向声明，我是新手不太会。具体出错的文件和提示如下：
2631	204	subVersion\d3d9\d3d9.h	[Error] 'D3DOVERLAYCAPS' has not been declared
2661	98	\subVersion\d3d9\d3d9.h	[Error] 'D3DCONTENTPROTECTIONCAPS' has not been declared
2662	49	\subVersion\d3d9\d3d9.h	[Error] 'D3DAUTHENTICATEDCHANNELTYPE' has not been declared
2702	66	\subVersion\d3d9\d3d9.h	[Error] 'D3DAUTHENTICATEDCHANNEL_CONFIGURE_OUTPUT' has not been declared
2744	118	\subVersion\d3d9\d3d9.h	[Error] 'D3DENCRYPTED_BLOCK_INFO' has not been declared

12	3	\subVersion\WeaponPreview.h	[Error] converting to execution character set: Illegal byte sequence
。。。。。。。。。。。。。

**Comment by AmazingPP** [comment]
请使用VS2017/VS2019编译
