### ISSUE TITLE
只有修改器打开的时候，才能生效

### ISSUE THREAD

**Issue by hhrensheng** [AmazingPP/subVerison_GTAV_Hack#46]
EPIC正版 故事模式。
无限子弹 无敌之类的选项 只有修改器打开的时候才管用。按F9 保存之后就失效了。这是为什么呢。打了NVE的补丁。

**Comment by AmazingPP** [comment]
修改器当然是只有在开启时有效果

**Comment by hhrensheng** [comment]
我的意思是 只有当修改器界面显示在游戏里时才会生效  如果按F9保存之后修改器界面消失就失效了。

**Comment by AmazingPP** [comment]
> 我的意思是 只有当修改器界面显示在游戏里时才会生效 如果按F9保存之后修改器界面消失就失效了。

F9是保存并关闭修改器

**Comment by hhrensheng** [comment]
我找到了 原来小键盘的减号能切换显示和隐藏。。。。。
