### ISSUE TITLE
dcBUG并没有修复 

### ISSUE THREAD

**Issue by hongsangdesu** [AmazingPP/subVerison_GTAV_Hack#48]

**Comment by hongsangdesu** [comment]
我使用了所有的解锁 结果还是无法开启第一次dc

**Comment by AmazingPP** [comment]
https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/f463b47ab917e13874414f086ce946e27483f6c3

我的失误，是一切关于GTAHax的功能都不能用了，加角色切换搞的，三目运算符少了个括号

新版已经重新Release了，再下一次就行了
