### ISSUE TITLE
1.3.5.2版本里的赌场和佩里科岛的前置解锁都没有效果，反而1.3.5.1的赌场前置解锁有效果

### ISSUE THREAD

**Issue by laridzhang** [AmazingPP/subVerison_GTAV_Hack#49]

**Comment by AmazingPP** [comment]
同 #48 

https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/f463b47ab917e13874414f086ce946e27483f6c3

我的失误，是一切关于GTAHax的功能都不能用了，加角色切换搞的，三目运算符少了个括号

新版已经重新Release了，再下一次就行了
