### ISSUE TITLE
希望能汉化车辆名称

### ISSUE THREAD

**Issue by YongHuMingJun** [AmazingPP/subVerison_GTAV_Hack#5]
希望能汉化车辆名称，我可以帮忙汉化

**Comment by AmazingPP** [comment]
如果时间允许的话,我会汉化车辆名称的

**Comment by YongHuMingJun** [comment]
> 如果时间允许的话,我会汉化车辆名称的

可以的话我可以帮忙汉化

**Comment by lixiangwuxian** [comment]
> 
> 
> > 如果时间允许的话,我会汉化车辆名称的
> 
> 可以的话我可以帮忙汉化

我已经汉化完成

**Comment by lixiangwuxian** [comment]
> 
> 
> 如果时间允许的话,我会汉化车辆名称的

已经提交Pull requests

**Comment by YongHuMingJun** [comment]
> > 如果时间允许的话,我会汉化车辆名称的
> 
> 已经提交Pull requests

感谢

**Comment by lixiangwuxian** [comment]
> 
> 
> > > 如果时间允许的话,我会汉化车辆名称的
> > 
> > 
> > 已经提交Pull requests
> 
> 感谢

早知道你要翻就我就不弄了，这玩意是真的累人，我有一半靠复制粘贴还花了三天，所以没看到你的issue。。。

**Comment by AmazingPP** [comment]
感谢 @lixiangwuxian 汉化车辆名称，已接受Pull Request
