### ISSUE TITLE
佩里科岛的解锁怎么用的，解锁不了

### ISSUE THREAD

**Issue by yaoyaoyoo** [AmazingPP/subVerison_GTAV_Hack#51]

**Comment by AmazingPP** [comment]
1.进入潜水艇，付费启动抢劫活动。
2.离开潜水艇（潜水艇的外面即可）
3.打开sub，杂项-线上-解锁-佩里科岛任务-所有的内容全部解锁一遍。
4.进入潜水艇，打开任务就是到分红关了
