### ISSUE TITLE
GTA V更新到1.53后，开小助手刷差事会把游戏卡掉

### ISSUE THREAD

**Issue by onlykiss01** [AmazingPP/subVerison_GTAV_Hack#69]
开小助手把佩里克岛前置弄好以后，准备开始分红关，开始终章任务后，游戏就卡崩了。不只是海岛，如果小助手开启后想进入其他差事，也会被卡掉游戏。请作者及时检测一下，给俺们更新更新吧

**Comment by onlykiss01** [comment]
游戏从1.52更到1.53了，估计是修复了一些漏洞吧

**Comment by AmazingPP** [comment]
已更新[v1.3.7](https://github.com/AmazingPP/subVerison_GTAV_Hack/releases/tag/v1.3.7)
