### ISSUE TITLE
辅助经常导致游戏崩溃！

### ISSUE THREAD

**Issue by piwawa** [AmazingPP/subVerison_GTAV_Hack#7]
今天第一次用这个国产辅助，开了人物半无敌，超级跳跃，在赌场豪劫和野外溜达的时候游戏突然卡死然后强退好几次，以前用Kiddon的mod从来没有出现过这种情况（排除电脑性能和防火墙问题），希望作者改善下程序代码以减少崩溃情况！

**Comment by AmazingPP** [comment]
请添加我的discord   mAsk°#4609

**Comment by AmazingPP** [comment]
同 #1  ，已修复 [#4f225ee](https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/1d836837cc115545dda3a269201eff0a63ad8e97)
