### ISSUE TITLE
GTA5游戏版本更新到 1.53 后，SubVerison v1.3.5.2版本功能问题。

### ISSUE THREAD

**Issue by hanshuaize** [AmazingPP/subVerison_GTAV_Hack#71]
·【刷出载具】线上进入别人的任务时刷不出载具。
·【赌场豪劫分红修改】和朋友一起玩【赌场豪劫】的时候，分红设置一激活的话我朋友的分红页面显示的数字一直在 修改分红(85%) 与 未修改 (15%)分红 之间以较快的频率来回变换，但是基本上在朋友电脑上看到分红还原成 未修改分红(15%) 的同时用我的电脑按 [准备就绪] 按钮时我朋友那里正好又会变为修改过后的分红，任务完成时的最终现金收入会显示为 未修改(15%)分红 实际现金收入却是之前开局时朋友电脑上显示为 修改分红(85%) 后的收入）。

---（我用的Steam版。）
---（我朋友用的是EPIC版，并且没开任何修改器，纯原生态游戏）

**Comment by hanshuaize** [comment]
查看回答请不要在网页使用【翻译为中文】功能，否则会乱码。

**Comment by AmazingPP** [comment]
已更新[v1.3.7](https://github.com/AmazingPP/subVerison_GTAV_Hack/releases/tag/v1.3.7)

现在再尝试一下
