### ISSUE TITLE
使用个别功能时会闪退游戏，比如爆炸子弹或者超级跳跃等

### ISSUE THREAD

**Issue by huheshuangxing** [AmazingPP/subVerison_GTAV_Hack#75]
爆炸子弹打几枪就闪退，超级跳跃跳一下就闪退

**Comment by AmazingPP** [comment]
已修复[v1.3.7](https://github.com/AmazingPP/subVerison_GTAV_Hack/releases/tag/v1.3.7)

如果还有问题可以具体反馈，提供复现方法
