### ISSUE TITLE
刷车刷出的固定翼飞机没开起落架

### ISSUE THREAD

**Issue by YongHuMingJun** [AmazingPP/subVerison_GTAV_Hack#8]
刷车刷出的固定翼飞机没开起落架

**Comment by AmazingPP** [comment]
具体是哪一架飞机，可以提供名称吗？

**Comment by YongHuMingJun** [comment]
所有飞机

**Comment by lixiangwuxian** [comment]
> 
> 
> 具体是哪一架飞机，可以提供名称吗？



> 
> 
> 具体是哪一架飞机，可以提供名称吗？

位于”飞机“一栏的几乎全部的飞机

**Comment by AmazingPP** [comment]
已修复 [4e4f513](https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/4e4f5130b74dff44d38da22ddaa253436e8a9709)
