### ISSUE TITLE
建议增加自定义位置z轴

### ISSUE THREAD

**Issue by huxxx123** [AmazingPP/subVerison_GTAV_Hack#9]
看了下settings，只有x轴和y轴，无法精确传送
普通传送到导航点可以不用z轴，但是自定义位置缺少z轴无法精确定位到室内的某个地方

**Comment by AmazingPP** [comment]
已修复 [#4f225ee](https://github.com/AmazingPP/subVerison_GTAV_Hack/commit/1d836837cc115545dda3a269201eff0a63ad8e97)
